### ISSUE TITLE
Context aware announcement bar

### ISSUE THREAD

**Issue by bhajneet** [shabados/docs#10]
**Is your feature request related to a problem? Please describe.**
It would be better to directly link to the repo that the docs are opened to. So if someone is reading gurmukhi utils, the announcement bar should reference GU repo directly.

**Comment by saihaj** [comment]
As suggested here https://github.com/facebook/docusaurus/discussions/3892#discussioncomment-163049 we need to swizzle the component. Putting this on hold since it is not suggested to [swizzle components](https://v2.docusaurus.io/docs/cli/#docusaurus-swizzle) until beta is reached
