### ISSUE TITLE
differentiate tabs zone better

### ISSUE THREAD

**Issue by bhajneet** [shabados/docs#61]
it is hard to tell where tabs content ends. if it had a background it would help. it also helps to put a background on active tab (lighter than hover) which better shows that there are tabs to switch between.

sidenote: need to test on mobile

**Comment by saihaj** [comment]
@bhajneet  will this commit https://github.com/shabados/docs/pull/63/commits/b6cd0d7e311cf1c05d1db155483b4918c054e7d3 resolve this issue?
