### ISSUE TITLE
Move the link icon to left

### ISSUE THREAD

**Issue by saihaj** [shabados/docs#8]
**Is your feature request related to a problem? Please describe.**
Is it possible to bring `#` to left? similar to how GitHub has it 
![image](https://user-images.githubusercontent.com/44710980/97337112-dd57cf80-184d-11eb-873c-a98918c4a11b.png)
Originally posted https://github.com/shabados/docs/pull/7#pullrequestreview-517955930

**Comment by bhajneet** [comment]
Not a big deal
